### ISSUE TITLE
sox FAIL formats: can't open input  `-': WAVE: RIFF header not found

### ISSUE THREAD

**Issue by fitzgeraldkyle** [gravesjohnr/AlexaNotificationCurl#2]
When I issue ./alexa.sh "Tell me a joke" I get the following error. 

sox FAIL formats: can't open input  `-': WAVE: RIFF header not found

I'm executing from a Raspberry PI running Raspbian.

**Comment by fitzgeraldkyle** [comment]
I fixed this by specifying "-t wav" at the beginning of the sox command:

sox -t wav - -c 1 -r 16000 -e signed -b 16 -t wav - >> multipart_body.txt

**Comment by gravesjohnr** [comment]
Interesting the -t wav at the end was not picked up.  I guess it needed to be before the - (stdin).

**Comment by EuphoriaCelestial** [comment]
I put the `-t wav` at the beginning but still got the same error, this is my command:

`sox -t wav audio_file.wav -r 16000 -b 16 converted_audio.wav channels 1`

**Comment by shiter007** [comment]
It may work.
`ffmpeg -i test1.wav -ar 16000 -ac 1 test2.wav`
