### ISSUE TITLE
Play error when running alexa.sh

### ISSUE THREAD

**Issue by sergiug** [gravesjohnr/AlexaNotificationCurl#3]
Hey,

Thank you for sharing your work with us!
Could you please help me with the following error? After performing all the steps, when running ./alexa.sh I get this error : 

./alexa.sh "Hey"
Question: Hey
Creating voice...
sox WARN wav: Premature EOF on .wav input file
Making request...
play FAIL formats: can't open input  `-':

**Comment by gravesjohnr** [comment]
Take a look at the script.  It is pretty simple.  From this error, it looks like you are missing or do not have the program pico2wave installed.
Look at line 85.
pico2wave -w /tmp/pipe.wav "${QUESTION}" | tee pico2wav.wav | sox - -c 1 -r 16000 -e signed -b 16 -t wav - >> multipart_body.txt
The error is from the 'sox' command.  This tells me the output of pico2wave is not working.  Try doing this step manually.
pico2wave -w /tmp/pipe.wav "test 1 2 3"
Then verify /tmp/pipe.wav is valid.
