### ISSUE TITLE
Keyerror with access and refresh tokens

### ISSUE THREAD

**Issue by Nathan1123** [gravesjohnr/AlexaNotificationCurl#6]
Hi,
I got to the point of running "auth_token.sh" and I consistently get this error:
```
File "<string>", line 1, in <module>
KeyError: 'auth_token'
```
Playing around with the code, I find that the request for the refresh token is giving the exact same error.  
When I try running "alexa.sh" anyway, I get this error:
`play FAIL formats: no handler for given file type `mp3'`
I'm not sure what the problem is. Has Amazon changed their security system, so this type of request is no longer valid? Or could there be something wrong with the version of curl I'm using?
Thanks,
Nathan

**Comment by Nathan1123** [comment]
Solved it myself. Did not include the serial number in the "auth_code.sh" script. I don't think the README file mentions having to use the serial number anywhere.

**Comment by gravesjohnr** [comment]
Nathan,

I'm glad this is sorted.  If you think the doco can be improved, please 
update it.


Thanks.

-John




------------------------------------------------------------------------

*From:* Nathan1123
*Sent:* Thursday, May 18, 2017 8:36AM
*To:* Gravesjohnr/alexanotificationcurl
*Cc:* Subscribed
*Subject:* Re: [gravesjohnr/AlexaNotificationCurl] Keyerror with access 
and refresh tokens (#6)
