### ISSUE TITLE
how to run on virtual machine without soundcard?

### ISSUE THREAD

**Issue by prankousky** [gravesjohnr/AlexaNotificationCurl#9]
hi,

i don't know how long i have been looking for this exact feature until i've found your awesome project. installed it on my mac and figured out how to operate my alexa (which speaks German) with espeak.

however, when i run the alexa.sh script on my virtual machine, i get an error like this:

```
./alexa.sh "alexa, wie geht es dir"
Question: alexa, wie geht es dir
Creating voice...
Making request...
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
play FAIL formats: can't open output file `default': snd_pcm_open error: No such file or directory
```

could you please help me figure this out? my node-red server runs on a virtual machine (ubuntu server 16.04.03) on my synology nas, so running the script on my mac wouldn't help much because it is not powered on 24/7.

thanks in advance :)

**Comment by gravesjohnr** [comment]
The script is trying to play the response and failing.  You can change the script to play the response in a different way.  Perhaps you could setup a REST service to play the response on another machine.  Or plug a bluetooth USB into your synology box and try to pair with a speaker.
